config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'
  get 'charges/create'
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers
  root "home#index"
  # resources :restaurants, only: [:index, :show, :new, :create, :destroy]
  resources :home
  resources :restaurant_cuisines, only: [:index]
  # resources :restaurants, only: [:index]
  # config/routes.
  resources :cart_items
  # config/routes.rb
  resources :orders do
    member do
      get 'show_details'
    end
  end

  resources :charges
  resources :dishes 
  # get '/contact', to: 'customer#contact', as: 'contact's
  resources :restaurants do
    member do
      get 'cuisines', to: 'restaurants#cuisines'
    end
  end
end 

app/models/address.rb
class Address < ApplicationRecord
  has_many :customer_addresses
  has_many :customers, through: :customer_addresses
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :dish
  end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :restaurant_cuisines
  has_many :restaurants, through: :restaurant_cuisines
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :customer_addresses
  has_many :addresses, through: :customer_addresses
  has_many :cart_items
  has_many :orders
  has_many :payments
  

end

app/models/customer_address.rb
class CustomerAddress < ApplicationRecord
    belongs_to :customer
    belongs_to :address 
end

app/models/dish.rb
class Dish < ApplicationRecord 
  # has_and_belongs_to_many :restaurant_cuisines
  belongs_to :restaurant_cuisine
  has_many :cart_items
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_one :payment
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :customer
    belongs_to :order
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :restaurant_cuisines
  has_many :cuisines, through: :restaurant_cuisines
  has_one :cart
end

app/models/restaurant_cuisine.rb
class RestaurantCuisine < ApplicationRecord
  belongs_to :restaurant
  belongs_to :cuisine 
  has_many :dishes
end

app/controllers/dishes_controller.rb
# class DishesController < ApplicationController
#     def show_by_cuisine
#       @restaurant_cuisine = RestaurantCuisine.find(params[:restaurant_cuisine_id])
#       @dishes = @restaurant_cuisine.dishes
#     end
  
    
class DishesController < ApplicationController  
  def index
    restaurant_cuisine = RestaurantCuisine.find_by(id: params[:id])
    if restaurant_cuisine.present?
      @dishes = restaurant_cuisine.dishes
      if @dishes.present?
        render "dishes/index"
      else
        flash[:notice] = "No dishes found for this cuisine."
        redirect_to home_index_path # Redirect to another page or take appropriate action
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
    if !customer_signed_in?
    #   redirect_to root_path # Redirect signed-in users to another page if needed
    # else
      redirect_to new_customer_session_path
    end
    @restaurants = Restaurant.all
    @cuisines=Cuisine.all
  end
  
  def show 
    
  end


  private 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/dish/index.html.erb
<h1>Restaurant Cuisines</h1>
<ul>
  <% @dishes.each do |dish| %>
    <li><%= dish.name %></li>
  <% end %>
</ul>

app/views/dish/show.html.erb
<!-- app/views/restaurant_cuisines/show.html.erb -->

<h1>Cuisine: <%= @restaurant_cuisine.cuisine.name %></h1>
<p>Restaurant: <%= @restaurant_cuisine.restaurant.name %></p>

<%= link_to "View Dishes", restaurant_cuisine_dishes_path(@restaurant_cuisine) %>

app/views/dishes/index.html.erb
<h1>Restaurant Cuisines</h1>
<ul>
  <%= form_tag cart_items_path, method: :post do  %>
    <% @dishes.each do |dish| %>
      <div class="dish-fields">
      <label> Dish Name:</label> <%= dish.name %><br>
      <label> Dish Price:</label> <%= dish.price %><br>
      <label> Dish Quantity:</label> <%= number_field_tag "selected_dishes[][quantity]" %>
      <%= hidden_field_tag "selected_dishes[][dish_name]", dish.name %>
      <%= hidden_field_tag "selected_dishes[][price]", dish.price %><br>
      <%= hidden_field_tag "selected_dishes[][dish_id]", dish.id %><br>
      <label>Add in Cart </label>
        <%= check_box_tag "selected_dishes[][check]", true %><br>
      </div>
    <% end %>
    <%= submit_tag 'Create Cart Item' %>
  <% end %>
</ul>