config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'
  get 'charges/create'
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers
  root "home#index"
  # resources :restaurants, only: [:index, :show, :new, :create, :destroy]
  resources :home
  resources :restaurant_cuisines, only: [:index]
  # resources :restaurants, only: [:index]
  # config/routes.
  resources :cart_items
  # config/routes.rb
  resources :orders do
    member do
      get 'show_details'
    end
  end

  resources :charges
  resources :dishes 
  # get '/contact', to: 'customer#contact', as: 'contact's
  resources :restaurants do
    member do
      get 'cuisines', to: 'restaurants#cuisines'
    end
  end
end 

app/models/address.rb
class Address < ApplicationRecord
  has_many :customer_addresses
  has_many :customers, through: :customer_addresses
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :dish
  end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :restaurant_cuisines
  has_many :restaurants, through: :restaurant_cuisines
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :customer_addresses
  has_many :addresses, through: :customer_addresses
  has_many :cart_items
  has_many :orders
  has_many :payments
  

end

app/models/customer_address.rb
class CustomerAddress < ApplicationRecord
    belongs_to :customer
    belongs_to :address 
end

app/models/dish.rb
class Dish < ApplicationRecord 
  # has_and_belongs_to_many :restaurant_cuisines
  belongs_to :restaurant_cuisine
  has_many :cart_items
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_one :payment
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :customer
    belongs_to :order
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :restaurant_cuisines
  has_many :cuisines, through: :restaurant_cuisines
  has_one :cart
end

app/models/restaurant_cuisine.rb
class RestaurantCuisine < ApplicationRecord
  belongs_to :restaurant
  belongs_to :cuisine 
  has_many :dishes
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
    if !customer_signed_in?
    #   redirect_to root_path # Redirect signed-in users to another page if needed
    # else
      redirect_to new_customer_session_path
    end
    @restaurants = Restaurant.all
    @cuisines=Cuisine.all
  end
  
  def show 
    
  end


  private 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/home/index.html.erb
<!-- views/home/index.html.erb -->

<% if customer_signed_in? %>
  <div class="welcome-box">
    <h2 class="welcome-heading">Welcome <%= current_customer.username %></h2>
  </div>
<% else %>
  <%= button_to "Sign in", new_customer_session_path, class: "sign-in-button" %>
<% end %>

<h2 class="restaurants-heading">Restaurants List</h2>
<div>

  <% @restaurants.each do |restaurant| %>
    
      <h2><%= restaurant.name %></h2>
      <p>Opening hours: <%= restaurant.opening_hours %></p>
      <p>Rating: <%= restaurant.rating %></p>
      <p>Contact number: <%= restaurant.contact_number %></p>
    
      <% restaurant.restaurant_cuisines.each do |rest_cuisine| %>
        <li>
          <%= link_to rest_cuisine.cuisine.name, dishes_path(id: rest_cuisine.id) %>
        </li>
      <% end %>
    </ul>
  <% end %>
</ul>
</div>
<%= button_to "Sign out", destroy_customer_session_path, method: :delete, class: "sign-out-button" %>
<%= stylesheet_link_tag 'custom' %> <!-- Link the custom.css stylesheet -->